services:
    migrate:
        build:
            context: ./
            dockerfile: ./backend/migrate.Dockerfile
        env_file:
            ./.env.keys
        depends_on:
            - postgres

    backend:
        container_name: backend
        build:
            context: ./
            dockerfile: ./backend/Dockerfile
        depends_on:
            migrate:
                condition: service_completed_successfully
            redis:
                condition: service_healthy
        env_file:
            ./.env.keys
    frontend:
        build:
            context: ./
            dockerfile: ./frontend/Dockerfile
        ports: 
            - 8080:3000
        env_file:
            ./.env.keys
        networks:
            - default
            - public_net

networks:
    public_net:
        external: true

include:
    - ./compose.db.yml
