services:
    backend:
        container_name: backend
        build:
            context: ./
            dockerfile: ./backend/Dockerfile
        depends_on:
            redis:
                condition: service_healthy
            postgres:
                condition: service_healthy
        env_file:
            ./.env.keys
    frontend:
        build:
            context: ./
            dockerfile: ./frontend/Dockerfile
        ports: 
            - 8080:3000
        depends_on:
            - backend
        env_file:
            ./.env.keys
        networks:
            - default
            - public_net

networks:
    public_net:
        external: true

include:
    - ./compose.db.yml
