services:
    postgres:
        container_name: drizzle-postgres
        environment:
            - POSTGRES_PASSWORD=mypassword
            - POSTGRES_USER=postgres
        ports:
            - 5432:5432
        image: postgres
